
project_id = "srnwogrjwhqjjyodxalx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://srnwogrjwhqjjyodxalx.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.plan-expiration-checker]
verify_jwt = false

[functions.auto-notification-sender]
verify_jwt = false

[functions.admin-chat-handler]
verify_jwt = false

[edge-runtime]
policy = "per_worker"
